# Cache modules in between jobs
cache:
  paths:
    - node_modules
    - .yarn-cache

stages:
  - build
  - test
  - coverage
  - deploy

# before_script:
#   - yarn --pure-lockfile --cache-folder .yarn-cache

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - yarn --pure-lockfile --cache-folder .yarn-cache
    - yarn run build:book-my-movie

unit-tests:
  image: trion/ng-cli-karma
  stage: test
  only:
    - dev
  artifacts:
    when: always
    paths:
      - coverage/
  script:
    - yarn run test:ci
  allow_failure: true

pages:
  image: alpine
  stage: coverage
  dependencies:
    - unit-tests
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public/
  only:
    - dev

deploy-production:
  stage: deploy
  dependencies:
    - app-build
  script:
    - firebase use prod
    - yarn run deploy
  only:
    - master
    - merge_requests
